config/routes.rb
Jungola::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations", :invitations => "invitations"}

  resources :updates_requests, :only => [:create]

  resources :comments, :only => [:create, :update] do
    member do
      post :update
    end
  end

  match 'groups/:id/join', :controller => :groups, :action => :join, :via => [:post, :get], :as => "join"

  match 'groups/:id/link', :controller => :groups, :action => :link, :via => [:post, :get], :as => "link"

  resources :users, :only => :show
  resources :groups do
    member do
      post :administer
      post :approve_user
      delete :approve_user
      post :approve_group
      delete :approve_group
    end
    resources :discussions do
      member do
        get :share
        post :share
        put :share
        post :update
      end
    end
    resources :documents do
      member do
        get :share
        post :share
        put :share
        post :update
      end
    end
    resources :todos do
      member do
        get :share
        post :share
        post :update
        put :share
      end
      resources :tasks do
        member do
          post :update
        end
      end
    end
  end

  resources :filter, :only => :index do
    collection do
      post :filter
      post :select
    end
  end

  match '/invite', :to => 'pages#invite'

  match '/user' => "filter#index", :as => :user_root

  root :to => 'pages#welcome'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  attr_accessible :body

  belongs_to :item, :polymorphic => true
  belongs_to :user

  validates :body, :presence => true

  def item
    self.item
  end

end

# == Schema Information
#
# Table name: comments
#
#  id         :integer         not null, primary key
#  user_id    :integer
#  body       :text
#  item_type  :string(255)
#  item_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_group, :find_item, :only => :create
  before_filter :find_comment, :only => :update
  before_filter :require_view, :only => :create

  def create
    @comment = current_user.comments.build(params[:comment])
    respond_to do |format|
      if @comment.save #SUCCESS
        if @todo
          @todo.comments << @comment
          @todo.update_attribute(:updated_at, Time.now)
          @todo.interactions.create(:user => current_user, :summary => 'Commented on item')
          @todo.interactors.each do |user|
            @user = user
            InteractionMailer.new_comment(@comment, user, @todo).deliver unless user == @comment.user
          end
          format.html { redirect_to group_todo_path(@group, @todo), notice: 'Comment was successfully created.' }
          format.json { render json: @comment, status: :created, location: @comment }
        elsif @discussion
          @discussion.comments << @comment
          @discussion.update_attribute(:updated_at, Time.now)
          @discussion.interactions.create(:user => current_user, :summary => 'Commented on item')
          @discussion.interactors.each do |user|
            @user = user
            InteractionMailer.new_comment(@comment, user, @discussion).deliver unless user == @comment.user
          end
          format.html { redirect_to group_discussion_path(@group, @discussion), notice: 'Comment was successfully created.' }
          format.json { render json: @comment, status: :created, location: @comment }
        elsif @document
          @document.comments << @comment
          @document.update_attribute(:updated_at, Time.now)
          @document.interactions.create(:user => current_user, :summary => 'Commented on item')
          @document.interactors.each do |user|
            @user = user
            InteractionMailer.new_comment(@comment, user, @document).deliver unless user == @comment.user
          end
          format.html { redirect_to group_document_path(@group, @document), notice: 'Comment was successfully created.' }
          format.json { render json: @comment, status: :created, location: @comment }
        end
      else
        if @todo
          format.html { render :template => 'todos/show' }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        elsif @discussion
          format.html { render :template => 'discussions/show' }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        elsif @document
          format.html { render :template => 'documents/show' }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def update
    if request.post? && @comment.user == current_user
      if @comment.update_attributes(params[:comment])
        render :text => params[:comment][:body]
      else
        render :nothing => true
      end
    else
      render :nothing => true
    end
  end

  private

    def find_group
      @group = Group.find(params[:group][:id])
    end

    def find_item
      if params[:todo]
        @todo = Todo.find params[:todo][:id]
      elsif params[:discussion]
        @discussion = Discussion.find params[:discussion][:id]
      elsif params[:document]
        @document = Document.find params[:document][:id]
      end
    end

    def find_comment
      @comment = Comment.find(params[:id])
    end

    def require_view
      @item ||= @todo
      @item ||= @discussion
      @item ||= @document
      unless current_user.can_view?(@group, @item)
        flash[:error] = "You don't have permission to comment on that."
        redirect_to @group
      end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% comment_class = current_user==comment.user ? "edit_comment" : "" %>
<div class="comment">
  <p class='comment-meta'>
    <span class="comment-user">
      <%= comment.user.present? ? link_to(comment.user.name, comment.user) : "[User Deleted]" %></span> |
    <%= timeago(comment.updated_at, {:class => 'comment-time'}) %>
  </p>
  <p class="comment-body <%= comment_class %>" id="<%= comment_path(comment) %>">
    <%= comment.body %>
  </p>
</div>

app/views/comments/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
  <%= f.label :body, "Comment" %><br />
  <%= f.text_area :body %>
</div>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= form_for @comment do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit 'Update Comment' %>
  </div>
<% end %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>User</th>
    <th>Body</th>
    <th>Item type</th>
    <th>Item</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.user_id %></td>
    <td><%= comment.body %></td>
    <td><%= comment.item_type %></td>
    <td><%= comment.item_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= form_for @comment do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit 'Post Comment' %>
  </div>
<% end %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Item type:</b>
  <%= @comment.item_type %>
</p>

<p>
  <b>Item:</b>
  <%= @comment.item_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>