config/routes.rb
Jungola::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations", :invitations => "invitations"}

  resources :updates_requests, :only => [:create]

  resources :comments, :only => [:create, :update] do
    member do
      post :update
    end
  end

  match 'groups/:id/join', :controller => :groups, :action => :join, :via => [:post, :get], :as => "join"

  match 'groups/:id/link', :controller => :groups, :action => :link, :via => [:post, :get], :as => "link"

  resources :users, :only => :show
  resources :groups do
    member do
      post :administer
      post :approve_user
      delete :approve_user
      post :approve_group
      delete :approve_group
    end
    resources :discussions do
      member do
        get :share
        post :share
        put :share
        post :update
      end
    end
    resources :documents do
      member do
        get :share
        post :share
        put :share
        post :update
      end
    end
    resources :todos do
      member do
        get :share
        post :share
        post :update
        put :share
      end
      resources :tasks do
        member do
          post :update
        end
      end
    end
  end

  resources :filter, :only => :index do
    collection do
      post :filter
      post :select
    end
  end

  match '/invite', :to => 'pages#invite'

  match '/user' => "filter#index", :as => :user_root

  root :to => 'pages#welcome'

end

app/views/notifier/approved_group.html.erb
Hey <%= link_to @admin.name, user_root_url %>!<br />
<br />
Your group (<%= link_to @my_group.name, group_url(@my_group) %>) is now connected with <%= link_to @new_group.name, group_url(@new_group)%>. Start working together by sharing to-do lists, discussions, and documents. It's the easiest way to plan joint projects and events.<br/>
<br/>
Sincerely,<br />
Jungol Team

app/views/notifier/approved_user.html.erb
Hey <%= link_to @user.name, user_root_url %>!<br />
<br />
Congratulations!  Your membership has been approved for “<%= link_to @group.name, group_url(@group) %>”.<br/>
<br/>
Group members can do a lot on Jungol.  Collaborate with your group members using to-do lists, discussions, and file-sharing.  If multiple organizations are working together, you can share these tools between groups.  <%= link_to "Get started with #{@group.name}.", group_url(@group) %><br/>
<br/>
Sincerely,<br />
Jungol Team

app/views/notifier/email_signup.html.erb
<p>
  Hey, you.
</p>

<p>
  Someone just requested to be notified of Jungol updates.
</p>
<p>
  Their email is <%= @email %>.
</p>
<p>
  They signed up from the IP <%= @ip %> at <%= @time %>.<br />
</p>
<br />

Have a great day.<br />
--Ryland

app/views/notifier/pending_group.html.erb
<p>Hello, <%= @admin.name %>!</p>

<p>As an administrator of <%= link_to @group.name, group_url(@group) %>, we wanted to let you know that <%= link_to @group_b.name, group_url(@group_b) %> has requested to connect with your group.</p>
<p>Once connected, you can share items (To-Dos, Discussions, Documents) with each other.  You can accept or deny their request through the following link.</p>

<p><%= link_to 'View pending connection(s)', group_url(@group) %></p>

<p>
  Have a Great Day!
  <br>
  <br>
  --<br>
  Jungol Team<br>
  (Sent automatically)
</p>

app/views/notifier/pending_user.html.erb
<p>Hello, <%= @admin.name %>!</p>

<p>As an administrator of <%= link_to @group.name, group_url(@group) %>, we wanted to let you know that <%= link_to @user.name, user_url(@user) %> has requested to join your group.</p>
<p>You can accept or deny their request through the following link.</p>

<p><%= link_to 'View pending user(s)', group_url(@group) %></p>

<p>
  Have a Great Day!
  <br>
  <br>
  --<br>
  Jungol Team<br>
</p>