config/routes.rb
Jungola::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations", :invitations => "invitations"}

  resources :updates_requests, :only => [:create]

  resources :comments, :only => [:create, :update] do
    member do
      post :update
    end
  end

  match 'groups/:id/join', :controller => :groups, :action => :join, :via => [:post, :get], :as => "join"

  match 'groups/:id/link', :controller => :groups, :action => :link, :via => [:post, :get], :as => "link"

  resources :users, :only => :show
  resources :groups do
    member do
      post :administer
      post :approve_user
      delete :approve_user
      post :approve_group
      delete :approve_group
    end
    resources :discussions do
      member do
        get :share
        post :share
        put :share
        post :update
      end
    end
    resources :documents do
      member do
        get :share
        post :share
        put :share
        post :update
      end
    end
    resources :todos do
      member do
        get :share
        post :share
        post :update
        put :share
      end
      resources :tasks do
        member do
          post :update
        end
      end
    end
  end

  resources :filter, :only => :index do
    collection do
      post :filter
      post :select
    end
  end

  match '/invite', :to => 'pages#invite'

  match '/user' => "filter#index", :as => :user_root

  root :to => 'pages#welcome'

end

app/models/group.rb
class Group < ActiveRecord::Base

  attr_accessor :agreement
  attr_accessible :name, :about, :agreement, :logo

  validates(:name, :presence => true,
            :length => {:maximum => 50},
            :uniqueness => { :case_sensitive => false })
  validates :about, :presence => true

  validates_acceptance_of :agreement

  validate :max_users

  after_create :add_creator_as_member

  #LOGO
  has_attached_file :logo, {
    :styles => { :medium => "300x100>", :thumb => "50x50>", :small => "30x30>" },
    :whiny => false
  }.merge(PAPERCLIP_IMAGE_OPTIONS)

  validates_attachment_size :logo, :less_than => 1.megabyte, :message => "must be less than 1MB in size"
  validates_attachment_content_type :logo, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/, :message => 'file type is not allowed (only jpeg/png/gif images)'

  #AFFILIATES
  has_many :group_connections, :dependent => :destroy
  has_many :groups, :through => :group_connections, :source => :group_b, :conditions => ['status = ?', 2], :order => 'name DESC'
  has_many :requested_groups, :through => :group_connections, :source => :group_b, :conditions => ['status = ?', 0], :order => 'name DESC'
  has_many :pending_groups, :through => :group_connections, :source => :group_b, :conditions => ['status = ?', 1], :order => 'name DESC'

  #MEMBERSHIPS
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships
  has_many :members, :through => :memberships, :source => :user, :conditions => ['is_pending = ?', false]
  has_many :pending_members, :through => :memberships, :source => :user, :conditions => ['is_pending = ?', true]

  #CREATOR
  belongs_to :creator, :foreign_key => 'creator_id', :class_name => 'User'

  #ITEMS
  has_many :item_shares, :dependent => :destroy
  has_many :shared_todos, :through => :item_shares, :source => :item, :source_type => 'Todo', :order => 'updated_at DESC'
  has_many :todos, :dependent => :destroy

  has_many :shared_discussions, :through => :item_shares, :source => :item, :source_type => 'Discussion', :order => 'updated_at DESC'
  has_many :discussions, :dependent => :destroy

  has_many :shared_documents, :through => :item_shares, :source => :item, :source_type => 'Document', :order => 'updated_at DESC'
  has_many :documents, :dependent => :destroy

  def approve_user(user)
    if pending_members.include?(user)
      user.memberships.find_by_group_id(self.id).update_attributes(:is_pending => false)
    end
  end

  def member?(user)
    members.include?(user)
  end

  def pending_member?(user)
    pending_members.include?(user)
  end

  def admin?(user)
    admins.include?(user) if user
  end

  def users_by_role
    members.all(:conditions => ['users.id not in (?)', self.creator], :include => :memberships, :order => 'memberships.role DESC' )
  end

  def admins
    members.includes(:memberships).where(:memberships => {:role => 1})
  end

  def non_admins
    members.includes(:memberships).where(:memberships => {:role => 2})
  end

  def non_admin?(user)
    non_admins.include?(user) if user
  end

  def unshared_groups(item)
    Group.find(:all, :conditions => ['id in (?)', self.groups - item.shared_groups])
  end

  def unconnected_groups
    if self.group_connections.present?
      Group.find(:all, :conditions => ['id not in (?) and id not in (?)', self.groups | self.pending_groups | self.requested_groups, self.id])
    else
      Group.find(:all, :conditions => ['id not in (?)', self.id])
    end
  end

  def shared_on_todos
    self.shared_todos.where "group_id not in ?", self.id
  end

  def shared_on_discussions
    self.shared_discussionss.where "group_id not in ?", self.id
  end

  def add_creator_as_member
    self.users << creator
    approve_user creator
  end

  def max_users
    if self.users.size > 30
      errors.add :base, "Group cannot have more than 30 users."
    end
  end

  def connect(group)
    if self.unconnected_groups.include? group
      req = self.group_connections.build(:group_b_id => group.id)
      pend = group.group_connections.build(:group_b_id => self.id, :status => 1)
      req.save! && pend.save!
    else
      return false
    end
  end

  def approve_group(group)
    req = self.group_connections.find_by_group_b_id(group.id)
    pend = group.group_connections.find_by_group_b_id(self.id)
    req.update_attributes(:status => 2) && pend.update_attributes(:status => 2)
  end

  def deny_group(group)
    req = self.group_connections.find_by_group_b_id(group.id)
    pend = group.group_connections.find_by_group_b_id(self.id)
    req.destroy && pend.destroy
  end

  def notify_of_new_connection(group)

    self.admins.each do |user|
      Notifier.approved_group(user, self, group).deliver
    end
  end

end




# == Schema Information
#
# Table name: groups
#
#  id                :integer         not null, primary key
#  name              :string(255)
#  about             :text
#  creator_id        :integer
#  created_at        :datetime
#  updated_at        :datetime
#  logo_file_name    :string(255)
#  logo_content_type :string(255)
#  logo_file_size    :integer
#  logo_updated_at   :datetime
#

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_group, :except => [:index, :new, :create]
  before_filter :require_admin, :only => [:destroy, :edit, :update, :link, :administer, :approve_user, :approve_group]

  def index
    @title = "All Groups"
    @blurb = "Search all the groups on Jungol to find the one for you. If you don't see what you're looking for, why not create a group?"
    @groups = Group.paginate(:page => params[:page])
  end

  def new
    @title = "Create Group"
    @group = Group.new
    @blurb = "Create a new group to share with the world."
  end

  def show
    @member = @group.member?(current_user)
    @pending = @group.pending_member?(current_user)
    @admin = @group.admin?(current_user)
    @title = @group.name
  end

  #ADD MEMBER TO GROUP
  def join
    if request.post?
      if !@group.users.include?(current_user)
        @group.users << current_user
        flash[:success] = "Thanks! Your membership must now be approved by an admin of #{@group.name}."

        #SEND OUT NOTIFICATION EMAILS
        @group.admins.each do |admin|
          Notifier.pending_user(admin, @group, current_user).deliver
        end

        redirect_to @group
      else
        flash[:error] = "Error requesting to join #{@group.name}. Please try again."
        redirect_to @group
      end
    else #it fell back to GET (no js)
      flash[:error] = "Please enable javascript to join."
      redirect_to @group
    end
  end

  #ADD GROUP TO GROUPS
  def link
    @title = "Group Connections"
    if request.get?
      render :link
    elsif request.xhr? #REQUEST LINK
      response_text = {:flash => {}, :text => {}}
      @group2 = Group.find(params[:group][:id])
      if @group.connect(@group2)
        response_text[:flash] = "Pending"

        #SEND OUT NOTIFICATION EMAILS
        @group2.admins.each do |admin|
          Notifier.pending_group(admin, @group2, @group).deliver
        end
      else
        response_text[:flash] = "Error."
      end
      render :json => response_text
      return
    elsif request.post?
      @group2 = Group.find(params[:group][:id])
      if @group.connect(@group2)
        flash[:success] = "Thanks. #{@group2.name} must now approve the connection."

        #SEND OUT NOTIFICATION EMAILS
        @group2.admins.each do |admin|
          Notifier.pending_group(admin, @group2, @group).deliver
        end
      else
        flash[:error] = "Error connecting with #{@group2.name}. Please try again."
      end
      redirect_to @group
    else
      flash[:error] = "Error connecting with #{@group2.name}. Please try again."
      redirect_to @group
    end
  end

  def create
    @group = current_user.created_groups.new(params[:group])
    if @group.save #success
      flash[:success] = "Group Created."
      redirect_to @group
    else
      flash.now[:error] = "Error creating group"
      @title = "Create Group"
      render :new
    end
  end

  def edit
    @title = "Edit Group"
  end

  def update
    if(@group.update_attributes(params[:group]))
      flash[:success] = "Group updated."
      redirect_to @group
    else
      @title = "Edit Group"
      render :edit
    end
  end

  def administer
    if params[:u].present? && params[:r].present?
      mem = Membership.find_by_user_id_and_group_id(params[:u], @group.id)
      if mem.change_role(params[:r])
        flash[:success] = "Member's role updated."
      end
      redirect_to @group
    end
  end

  #Approve/Deny pending memberships
  def approve_user
    if params[:u].present?
      if request.post? #Approve
        mem = Membership.find_by_user_id_and_group_id(params[:u], @group.id)
        if mem.update_attributes(:is_pending => false)
          flash[:success] = "Membership approved."
          mem.notify_user
        end
      elsif request.delete? #DENY
        mem = Membership.find_by_user_id_and_group_id(params[:u], @group.id)
        if mem.destroy
          flash[:success] = "Membership denied."
        end
      end
    end
    redirect_to @group
  end

  #Approve/Deny pending group connections
  def approve_group
    if params[:g].present?
      if request.post? #Approve
        @group2 = Group.find(params[:g])
        if @group.approve_group(@group2)
          flash[:success] = "You're now connected to #{@group2.name}."
          @group.notify_of_new_connection(@group2)
        end
      elsif request.delete? #DENY
        @group2 = Group.find(params[:g])
        if @group.deny_group(@group2)
          flash[:success] = "Connection denied."
        end
      end
    end
    redirect_to @group
  end

  def destroy
    title = @group.name
    if current_user == @group.creator
      if @group.destroy
        flash[:success] = "Group '#{title}' deleted."
        current_user.update_attributes(:filter_state => nil)
        redirect_to root_path
      end
    else
      flash[:error] = "Error deleting Group '#{title}.'"
      redirect_to group_path @group
    end
  end

  def find_group
    @group = Group.find(params[:id])
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class='field'>
  <%= f.label :name %> <br />
  <%= f.text_field :name %>
</div>
<div class='field'>
  <%= f.label :about %> <br />
  <%= f.text_area :about %>
</div>
<div class='field'>
  <%= f.label 'Group Logo' %><br />
  <%= f.file_field :logo %>
</div>

app/views/groups/_group.html.erb
<li class='group-list-li'>
  <div class="group-img">
    <%= render 'groups/logo', :group => group, :size => 50 %>
  </div>
  <div class="group-text">
    <%= content_tag :span, link_to(group.name, group), :class => 'group-link' %><br />
    <span class="group-mems"><%= pluralize group.members.count, "member"  %></span> |
    <span class="group-cons"><%= pluralize group.groups.count, "connection"  %></span>
  </div>
  <div class="clearall"></div>
</li>

app/views/groups/_group_conn.html.erb
<li class='group-list-li'>
  <div class="group-img">
    <%= render 'groups/logo', :group => group, :size => 50 %>
  </div>
  <div class="group-text">
    <%= content_tag :span, link_to(group.name, group), :class => 'group-link' %><br />
    <span class="group-mems"><%= pluralize group.members.count, "member"  %></span> |
    <span class="group-cons"><%= pluralize group.groups.count, "connection"  %></span>
  </div>
  <div class = "group-status">
    <% if conn==0 %>
      <%= form_tag(link_path(@group), :method => :post, :remote => true) do %>
        <%= hidden_field(:group, :id, :value => group.id) %>
        <%= submit_tag "Connect", :class => 'group-share' %>
      <% end %>
    <% elsif conn==1 %>
      <span class='status'>Pending</span>
    <% elsif conn==2 %>
      <span class='status'>Connected!</span>
    <% end %>
  </div>
  <div class="clearall"></div>
</li>

app/views/groups/_logo.html.erb
<% if size == 50
      @size = :thumb
      @width = 50
    elsif size==30
      @size = :small
      @width = 30
    else
      @size = :medium
      @width = ""
    end %>
<% if group.logo.present? %>
  <%= link_to(image_tag(group.logo.url(@size), :alt => "#{group.name} Logo"), group_path(group)) %>
<% else %>
  <%= link_to(image_tag("group-img-default.png", :alt => "#{group.name} Logo", :width => @width), group_path(group)) %>
<% end %>

app/views/groups/_pending_group.html.erb
<% can_approve = current_user.privileged? @group %>
<li class='group-list-li'>
  <div class="group-img">
    <%= render 'groups/logo', :group => group, :size => 50 %>
  </div>
  <div class="group-text">
    <%= content_tag :span, link_to(group.name, group), :class => 'group-link' %><br />
    <span class="group-mems"><%= pluralize group.users.count, "member"  %></span> |
    <span class="group-cons"><%= pluralize group.groups.count, "connection"  %></span>
    <p class='group-status'>
      <span class="group status">Pending Connection</span>
      <% if can_approve %>
        <span class="links">
          <%= link_to("Approve", approve_group_group_path(@group, :g => group.id), :method => 'POST', :class => 'pend') %>
          <%= link_to("Deny", approve_group_group_path(@group, :g => group.id), :method => 'DELETE', :class => 'pend') %>
        </span>
      <% end %>
    </p>
  </div>
  <div class="clearall"> </div>
</li>

app/views/groups/_pending_user.html.erb
<% is_creator = current_user==@group.creator %>
<li class='group-member'>
  <div class="user-img">
    <%= render 'users/avatar', :user => user, :size => 30 %>
  </div>
  <div class="user-text">
    <span class="user-link">
      <%= link_to user.name, user %>
    </span>
    <p class="user-status">
      <span class='user status role'>Pending</span>
      <% if is_creator %>
          <%= link_to("Approve", approve_user_group_path(@group, :u => user.id), :method => 'POST', :class => 'pend') %>
          <%= link_to("Deny", approve_user_group_path(@group, :u => user.id), :method => 'DELETE', :class => 'pend') %>
      <% end %>
    </p>
  </div>
  <div class="clearall"> </div>
</li>

app/views/groups/_requested_group.html.erb
<li class='group-list-li'>
  <div class="group-img">
    <%= render 'groups/logo', :group => group, :size => 50 %>
  </div>
  <div class="group-text">
    <%= content_tag :span, link_to(group.name, group), :class => 'group-link' %><br />
    <span class="group-mems"><%= pluralize group.users.count, "member"  %></span> |
    <span class="group-cons"><%= pluralize group.groups.count, "connection"  %></span>
    <p class='group-status'> <span class="group status">Connection Requested</span> </p>
  </div>
  <div class="clearall"> </div>
</li>

app/views/groups/_shared_item.html.erb
<li>
  <% if item.is_a? Discussion %>
    <%= link_to item.title, group_discussion_path(@group, item) %>
    (<%= item.class %>)
  <% elsif item.is_a? Todo %>
    <%= link_to item.title, group_todo_path(@group, item) %>
    (<%= item.class %>)
  <% end %>
</li>

app/views/groups/_user.html.erb
<% is_creator = current_user==@group.creator %>
<li class='group-member'>
  <div class="user-img">
    <%= render 'users/avatar', :user => user, :size => 30 %>
  </div>
  <div class="user-text">
    <span class="user-link">
      <%= link_to user.name, user %>
    </span>
    <p class="user-status">
        <% if user == @group.creator %>
          <%= content_tag :span, 'Creator', :class => 'user role' %>
        <% elsif user.admin_of? @group %>
          <%= content_tag :span, 'Administrator', :class => 'user role' %>
          <%= link_to("Remove Admin", administer_group_path(@group, :u => user.id, :r => 2), :method => 'POST') if is_creator %>
        <% else %>
          <%= content_tag :span, 'User', :class => 'user role' %>
          <%= link_to("Make Admin", administer_group_path(@group, :u => user.id, :r => 1), :method => 'POST') if is_creator %>
        <% end %>
    </p>
  </div>
  <div class="clearall"></div>
</li>

app/views/groups/edit.html.erb
<div class="content-bg">
  <div id="group-edit" class="main-right full">
    <div class="alt-item-head headerfull">
      <h2>Edit Group</h2>
      <% if current_user == @group.creator %>
        <span class='group delete button'><%= link_to "DELETE GROUP", group_path(@group), :method => :delete, :confirm => "You sure?",
          :title => "Delete #{@group.name}" %></span>
      <% end %>
    </div>


    <%= form_for @group, :html => { :multipart => true } do |f| %>
      <p>
        <%= render('logo', :group => @group, :size => 300) %>
      </p>
      <div class='field'>
        <%= f.label 'Upload a Group Logo' %><br />
        <%= f.file_field :logo %>
      </div>
      <div class='field'>
        <%= f.label :about %> <br />
        <%= f.text_area :about %>
      </div>
      <div class='actions submit'>
        <%= f.submit "Update" %>
      </div>
    <% end %>

  </div>
</div>

app/views/groups/index.html.erb
<div class="content-bg">
  <div id="wrapper">

    <div id="all-groups" class="main-right full">
      <div class="alt-item-head headerfull">
        <h2>All Groups</h2>
      </div>
      <%= will_paginate %>

      <ul class='all-groups'>
        <%= render @groups %>
      </ul>

      <%= will_paginate %>

      <div class="clearall"></div>
    </div>
  </div>

app/views/groups/link.html.erb
<div class="content-bg">
  <div id="connect-group" class="main-right full">
    <div id='group-connect' class="item">
      <div class="alt-item-head headerfull">
        <h2><%= "Add a connection to #{@group.name}"%></h2>
      </div>
      <ul class='group-groups'>
        <% @group.unconnected_groups.each do |un| %>
          <%= render 'group_conn', :group => un, :conn => 0 %>
        <% end %>

        <% pending = @group.pending_groups | @group.requested_groups %>
        <% pending.each do |pn| %>
          <%= render 'group_conn', :group => pn, :conn => 1 %>
        <% end %>

        <% @group.groups.each do |gr| %>
          <%= render 'group_conn', :group => gr, :conn => 2 %>
        <% end %>
      </ul>
      <div class="clearall"></div>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="content-bg">
  <div id="group-new" class="main-right full">
    <div class="alt-item-head headerfull">
      <h2>Create Group</h2>
    </div>

    <%= form_for(@group) do |f| %>
      <%= render 'fields', :f => f %>
      <div class='field agreement'>
        <%= f.check_box :agreement %>
        <%= f.label :agreement, "I agree to the terms and conditions (forthcoming)" %>
      </div>
      <div class='actions submit'>
        <span class="group-fix"><%= f.submit "Create Group" %></span>
      </div>
    <% end %>

  </div>
</div>

app/views/groups/show.html.erb
<div class="content-bg">
  <div id="show-group" class="main-right full">
    <div class="alt-item-head headerfull">
      <h2>About</h2>
      <%= content_tag(:span, link_to("Request to Join »", join_path(@group), :method => :post), :class => 'join-button button', :id => 'join_button') unless @member || @pending %>
      <%= content_tag(:span, "Membership Pending", :class => :button) if @pending %>

    </div>
    <p><%= @group.about %></p>

    <div class="alt-item-head headerfull">
      <h2>Members</h2>
    </div>
    <ul class='group-members'>
      <% if @group.creator.present? %>
        <%= render 'user', :user => @group.creator %>
      <% else %>
        [Creator Deleted]
      <% end %>
      <% @group.users_by_role.each do |user| %>
        <%= render 'user', :user => user %>
      <% end %>

      <% if @admin && @group.pending_members.present? %>
        <% @group.pending_members.each do |p| %>
          <%= render 'pending_user', :user => p %>
        <% end %>
      <% end %>
      <div class="clearall"></div>
    </ul>

    <div class="alt-item-head headerfull">
      <h2>Connected Groups</h2>
      <%= content_tag(:span, link_to("Connect to Groups", link_path(@group)), :class => 'button', :id => 'link-button') if @admin %>
    </div>
    <ul class="group-groups">
      <% if @group.groups.present? %>
        <% @group.groups.each do |gr| %>
          <%= render 'group', :group => gr %>
        <% end %>
      <% else %>
        <li>No Groups yet.</li>
      <% end %>

      <% if @group.requested_groups.present? %>
        <% @group.requested_groups.each do |gr| %>
          <%= render 'requested_group', :group => gr %>
        <% end %>
      <% end %>

      <% if @admin && @group.pending_groups.present? %>
        <% @group.pending_groups.each do |g| %>
          <%= render 'pending_group', :group => g %>
        <% end %>
      <% end %>

      <div class="clearall"></div>
    </ul>

  </div>
</div>