config/routes.rb
Jungola::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations", :invitations => "invitations"}

  resources :updates_requests, :only => [:create]

  resources :comments, :only => [:create, :update] do
    member do
      post :update
    end
  end

  match 'groups/:id/join', :controller => :groups, :action => :join, :via => [:post, :get], :as => "join"

  match 'groups/:id/link', :controller => :groups, :action => :link, :via => [:post, :get], :as => "link"

  resources :users, :only => :show
  resources :groups do
    member do
      post :administer
      post :approve_user
      delete :approve_user
      post :approve_group
      delete :approve_group
    end
    resources :discussions do
      member do
        get :share
        post :share
        put :share
        post :update
      end
    end
    resources :documents do
      member do
        get :share
        post :share
        put :share
        post :update
      end
    end
    resources :todos do
      member do
        get :share
        post :share
        post :update
        put :share
      end
      resources :tasks do
        member do
          post :update
        end
      end
    end
  end

  resources :filter, :only => :index do
    collection do
      post :filter
      post :select
    end
  end

  match '/invite', :to => 'pages#invite'

  match '/user' => "filter#index", :as => :user_root

  root :to => 'pages#welcome'

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :title, :description, :doc

  belongs_to :group
  belongs_to :creator, :foreign_key => 'creator_id', :class_name => 'User'

  has_many :item_shares, :dependent => :destroy, :as => :item, :order => 'created_at ASC'
  has_many :shared_groups, :through => :item_shares, :source => :group
  has_many :comments, :dependent => :destroy, :as => :item, :order => 'created_at ASC'
  has_many :interactions, :dependent => :destroy, :as => :item
  has_many :interactors, :through => :interactions, :source => :user, :uniq => true

  validates( :title, :presence => true,
                      :length => {:maximum => 60},
                      :uniqueness => { :case_sensitive => false})

  validates :description, :presence => true

  def admin_share?(group)
    self.item_shares.find_by_group_id(group.id).admins_only
  end

  has_attached_file :doc, {
    :whiny => false
  }.merge(PAPERCLIP_DOC_OPTIONS)

  validates_attachment_presence :doc, :message => "must be present. You need to upload a file."
  validates_attachment_size :doc, :less_than => 4.megabyte, :message => "must be less than 4MB in size"
  validates_attachment_content_type :doc,
    :content_type => %w(image/jpg
                        image/jpeg
                        image/pjpeg
                        image/png
                        image/x-png
                        image/gif
                        application/pdf
                        application/msword
                        application/vnd.openxmlformats-officedocument.wordprocessingml.document
                        application/vnd.openxmlformats-officedocument.wordprocessingml.template
                        application/vnd.ms-word.document.macroEnabled.12
                        application/vnd.ms-word.template.macroEnabled.12 application/vnd.ms-excel
                        application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                        application/vnd.openxmlformats-officedocument.spreadsheetml.template
                        application/vnd.ms-excel.sheet.macroEnabled.12
                        application/vnd.ms-excel.template.macroEnabled.12
                        application/vnd.ms-excel.addin.macroEnabled.12
                        application/vnd.ms-excel.sheet.binary.macroEnabled.12
                        application/vnd.ms-powerpoint
                        application/vnd.openxmlformats-officedocument.presentationml.presentation
                        application/vnd.openxmlformats-officedocument.presentationml.template
                        application/vnd.openxmlformats-officedocument.presentationml.slideshow
                        application/vnd.ms-powerpoint.addin.macroEnabled.12
                        application/vnd.ms-powerpoint.presentation.macroEnabled.12
                        application/vnd.ms-powerpoint.template.macroEnabled.12
                        application/vnd.ms-powerpoint.slideshow.macroEnabled.12),
    :message => 'is not allowed (only images, .pdfs, and MS Office filetypes)'
end


# == Schema Information
#
# Table name: documents
#
#  id               :integer         not null, primary key
#  creator_id       :integer
#  group_id         :integer
#  title            :string(255)
#  description      :text
#  doc_file_name    :string(255)
#  doc_content_type :string(255)
#  doc_file_size    :integer
#  doc_updated_at   :datetime
#  created_at       :datetime
#  updated_at       :datetime
#

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_group, :except => :share
  before_filter :find_doc, :except => [:new, :create]
  before_filter :find_origin_group, :only => :share
  before_filter :require_member, :except => :show #catch them in require_view
  before_filter :require_delete, :only => [:destroy, :edit]
  before_filter :require_view, :except => [:new, :create]

  def new
    @title = "Create a Document"
    @document = Document.new
    @privileged = current_user.privileged? @group
    @blurb = "Create a new Document to share with the world."
  end

  def create
    @document = current_user.created_documents.build(params[:document])
    if @document.save #success
      @document.interactions.create(:user => current_user, :summary => 'Created Document')
      @group.documents << @document

      #create share with original group
      current_user.share @group, @document, (params[:admins_only].present?)

      flash[:success] = "Document Created."
      #HANDLE SHARING
      if params['share'].present?
        params['share'].each do |sh|
          new_share = current_user.created_shares.new()
          if sh[1].include? "admin"
            new_share.admins_only = true
          end
          if new_share.save
            @shared_group = Group.find(sh[0])
            @document.interactions.create(:user => current_user, :summary => 'Shared Document')
            @document.item_shares << new_share
            @shared_group.item_shares << new_share
            new_share.notify_users
          end
        end
      end
      redirect_to group_document_path(@group, @document)
    else
      @title = "Create a Document"
      render :new
    end
  end

  def edit
    @title = "Edit Document"
  end

  def show
    @title = "#{@document.title} < #{@group.name}"
    @comment = current_user.comments.new
    @unshared = @group.unshared_groups(@document)
    @shared = @document.shared_groups
    @up_path = group_document_path(@group, @document)
  end

  def update
    if request.post? #AJAX update - description
      if @document.update_attributes(params[:document])
        @document.update_attribute(:updated_at, Time.now)
        render :text => params[:document][:description]
        return
      end
    elsif request.put?
      if @document.update_attributes(params[:document])
        @document.update_attribute(:updated_at, Time.now)
        flash[:success] = "Document updated."
        redirect_to @document
      end
    end
    render :nothing => true
  end

  def share
    if request.get? # SHARE PAGE
      @title = "Share #{@document.title}"
      @unshared = @group.unshared_groups(@document)
      #@share = @current_user.created_shares.new()
      render :share
      return
    elsif request.xhr? #CREATE SHARE (AJAX)
      response_text = {:flash => {}, :text => {}}
      new_share = current_user.created_shares.new()
      #DID THEY CHECK THE BOX?
      if params[:admins_only].present?
        new_share.admins_only = true
      end

      if new_share.save
        @document = Document.find(params[:id])
        @document.interactions.create(:user => current_user, :summary => 'Shared Document')
        @document.item_shares << new_share
        @shared_group.item_shares << new_share
        new_share.notify_users
        response_text[:flash] = "'#{@document.title}' has been shared with #{@shared_group.name}."
      else
        response_text[:flash] = "Problem sharing document.  Please try again."
      end
      render :json => response_text
      return

    elsif request.post? #CREATE SHARE
      new_share = current_user.created_shares.new()
      if params[:admins_only].present?
        new_share.admins_only = true
      end

      if new_share.save
        @document = Document.find(params[:id])
        @document.interactions.create(:user => current_user, :summary => 'Shared Document')
        @document.item_shares << new_share
        @shared_group.item_shares << new_share
        new_share.notify_users
        flash[:success] = "'#{@document.title}' has been shared with #{@shared_group.name}."
      else
        flash[:error] = "Problem sharing document.  Please try again."
      end
    elsif request.put? #UPDATE SHARE

    elsif request.delete? #DELETE SHARE

    else #UNKNOWN

    end
    redirect_to group_document_path(@document.group, @document)
  end

  def destroy
    title = @document.title
    @document.destroy
    flash[:success] = "Document '#{title}' destroyed."
    redirect_to @group
  end

  private

    def find_group
      @group = Group.find(params[:group_id])
    end

    def find_doc
      @document = Document.find(params[:id])
    end

    def find_origin_group
      @group = @document.group
      @shared_group = Group.find(params[:group_id])
    end

    def require_delete
      unless current_user.can_delete? @document
        redirect_to group_document_path @group, @document
      end
    end

    def require_view
      unless current_user.can_view?(@group, @document)
        flash[:error] = "You don't have permission to do that."
        redirect_to @group
      end
    end

end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<li>
  <%= link_to document.title, group_document_path(@group, document) %>
  <% if !document.item_shares.empty? %><br />
    <ul>
      <% document.item_shares.each do |i| %>
        <%= render('documents/share', :group => i.group) unless i.group.id == @group.id %>
      <% end %>
    </ul>
  <% end %>
</li>

app/views/documents/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class = 'field' >
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>
<div class = 'field' >
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</div>
<div class='field'>
  <%= f.label 'Document upload' %><br />
  <%= f.file_field :doc %>
</div>

app/views/documents/_share_form.html.erb
<li class='share-li'>
  <%= form_tag(share_group_document_path(group, @document), :method => :post, :remote => true) do %>
    <% if current_user.privileged? @group %>
      <%= check_box_tag :admins_only %>
      <label for="admins_only">Admins Only</label>
    <% end %>
    <%= content_tag :span, group.name, :class => 'group-share' %>
    <%= submit_tag "Share", :class => 'group-share' %>
  <% end %>
</li>

app/views/documents/edit.html.erb
<div class="content-bg">
  <div id="main-right" class="main-right full">
    <div class="alt-item-head headerfull">
      <h2>Edit Document</h2>
    </div>

    <%= form_for @document, :html => { :multipart => true } do |f| %>
      <p> <%= render('doc', :document => @document) %> </p>

      <%= render 'fields', :f => f %>
      <div class='actions submit'>
        <%= f.submit "Update" %>
      </div>
    <% end %>
  </div>
</div>

app/views/documents/new.html.erb
<div class="content-bg">
  <div id="main-right" class="main-right full">
    <div class="alt-item-head headerfull">
      <h2>Create New Document</h2>
    </div>
    <%= form_for [@group, @document] do |doc_f| %>
      <%= render 'fields', :f => doc_f %>

      <div class = 'actions'>
        <% if current_user.privileged? @group %>
          <span class="admins_only">
            <%= check_box_tag :admins_only %>
            <%= label_tag :admins_only, "Only share with admins of #{@group.name}" %>
          </span>
        <% end %>
        <span class="doc-fix"><%= doc_f.submit "Create" %></span>
      </div>
    <% end %>
    
    <div id="group-share">
      <h3>Share with:</h3>
      <div class="group-share-copy">
        Do you want to share this document with your connections? Don't worry! You can always come back and share it later.
      </div>
      <p>
        <% if @group.groups.present? %>
          <%= check_box_tag :select_all %>
          <%= label_tag :select_all, "Select All" %>

          <% if current_user.privileged? @group %>
            <%= check_box_tag :all_admins %>
            <%= label_tag :all_admins, "Share only with Admins" %>
            <br />
          <% end %>
        <% else %>
          <span class="note" style='color:#696A57;'>Sorry, <%= @group.name %> must be connected with other groups to share.</span>
          <% if current_user.privileged? @group %>
            <br />
            <%= link_to "Connect with Other Groups", link_path(@group), :target => '_blank' %>
          <% end %>
        <% end %>
      </p>
      <ul class="share-list">
        <% if @group.groups.present? %>
          <% @group.groups.each do |g| %>
            <%= render 'items/group_share', :group => g %>
          <% end %>
        <% end %>
      </ul>
      <div class="clearall"></div>
    </div>
    <div class="clearall"></div>
  </div>
</div>

app/views/documents/share.html.erb
<div class="content-bg">
  <div id="doc-share" class="main-right full">
    <div class="alt-item-head headerfull">
      <h2>Share <%= @document.title %> with:</h2>
    </div>
    <% if @unshared.present? %>
      <ul class="share-list">
        <% @unshared.each do |group| %>
          <%= render 'share_form', :group => group %>
        <% end %>
      </ul>
    <% else %>
      <p><%= "#{@document.title} has been shared with all connected groups." %></p>
    <% end %>
    <div class="clearall"></div>
  </div>
</div>

app/views/documents/show.html.erb
<div class="content-bg">
  <div id="main-right" class="main-right full">
    <div class="alt-item-head headerfull">
      <h2><%= @document.title %></h2>
      <span id="comment-button" class="button"><a href="#comments">Comment</a></span>
      <span id="share-button" class="button"><a href="<%= share_group_document_path(@group, @document) %>">Share »</a></span>
      <div class="creator">
        Created by:
        <%= @document.creator.present? ? link_to(@document.creator.name, @document.creator) : "[User Deleted]" %>
      </div>
    </div>
    <% if @shared.present? %>
      <ul class="shared-list greenme">
        <li>Shared between:  </li>
        <% @shared.each do |group| %>
          <%= render 'items/shared_group', :group => group, :item => @document %>
        <% end %>
      </ul>
    <% end %>

    <% if current_user.can_delete? @document %>
      <span class='delete button'><%= link_to "DELETE DOCUMENT", group_document_path(@group, @document), :method => :delete, :confirm => "You sure?",
        :title => "Delete #{@document.title}" %></span>
    <% end %>

    <p id="<%= @up_path %>" class='item-desc edit_doc_desc'>
      <i><%= @document.description %></i>
    </p>
    <div id="doc-link">
      <%= link_to 'Download', @document.doc.url, :target => '_blank', :class => 'shiny-button' %><br />
      <%= content_tag(:div, @document.doc_file_name, :class => 'docname' ) %>
    </div>

    <%= form_for @comment do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>
      <%= hidden_field(:group, :id) %>
      <%= hidden_field(:document, :id) %>
      <div class="field">
        <a name="comments"></a>
        <p>Comments</p>
        <span><%= f.label :body, "Post Comment..." %></span><br />
        <%= f.text_area :body %>
      </div>
      <div class="actions">
        <%= f.submit 'Post Comment »' %>
      </div>
    <% end %>
    <div id="doc-comments">
      <%= render @document.comments %>
    </div>

  </div>
</div>